---
title: "Reg 2 final project"
author: "Angela Cheng"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data cleaning}
# load the data
library("AER")
data(NMES1988, package = "AER") 
help(NMES1988, package = "AER")
# 4406 obs and 19 variables

# creating new chronic
library(dplyr)
NMES1988<-NMES1988%>%mutate(
  new.chronic=case_when(
    chronic==0~0,
    chronic==1~1,
    chronic>=2~2
  )
)
```
```{r table1}
library(table1)
table1 <- table1::table1(~visits + age + income + gender + employed + insurance + health + new.chronic, data = NMES1988)
print(table1)
```

```{r model1 and fit test}
# since visit is a count of events, so we use a poisson model
# before using the poisson model, 
# check the mean and variance of the visit to see if it meets the assumption
mean(NMES1988$visits)
var(NMES1988$visits)
# mean=5.77 and variance=45.69 they are not close to each other
# so we cannot use a poission model
# use negative binomial regression instead
library(MASS)
model1 <- glm.nb(visits ~ age + income + gender + employed + insurance + health + new.chronic, 
                       data=NMES1988)
summary(model1)
# likelihood ratio test
null_model <- glm.nb(visits ~ 1, data = NMES1988)
lrtest(null_model,model1)
# BIC
BIC(model1)
```

```{r model1 and prediction}
test.data.ins0 = data.frame(insurance = "no", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="poor", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins0<-predict(model1, test.data.ins0, type = "response")
# show predicted value
predicted.value.ins0

test.data.ins1 = data.frame(insurance = "yes", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="poor", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins1<-predict(model1, test.data.ins1, type = "response")
# show predicted value
predicted.value.ins1
```
```{r model 2/3 fit}
model2 <- glm.nb(visits ~ age + income + gender + employed + insurance + health + new.chronic + insurance:gender, 
                 data=NMES1988)
# lr test
lrtest(model1,model2)

model3 <- glm.nb(visits ~ age + income + gender + employed + insurance + health + new.chronic + insurance:health, 
                 data=NMES1988)
# lr test
lrtest(model1,model3)

# model 3 is preferred
# model 3 prediction
# health poor without insurance
test.data.ins0healthp = data.frame(insurance = "no", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="poor", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins0healthp<-predict(model3, test.data.ins0healthp, type = "response")
# show predicted value
predicted.value.ins0healthp

# health avarage without insurance
test.data.ins0healtha = data.frame(insurance = "no", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="average", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins0healtha<-predict(model3, test.data.ins0healtha, type = "response")
# show predicted value
predicted.value.ins0healtha

# health excellent without insurance
test.data.ins0healthe = data.frame(insurance = "no", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="excellent", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins0healthe<-predict(model3, test.data.ins0healthe, type = "response")
# show predicted value
predicted.value.ins0healthe

# health poor with insurance
test.data.ins1healthp = data.frame(insurance = "yes", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="poor", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins1healthp<-predict(model3, test.data.ins1healthp, type = "response")
# show predicted value
predicted.value.ins1healthp

# health avarage without insurance
test.data.ins1healtha = data.frame(insurance = "yes", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="average", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins1healtha<-predict(model3, test.data.ins1healtha, type = "response")
# show predicted value
predicted.value.ins1healtha

# health excellent without insurance
test.data.ins1healthe = data.frame(insurance = "yes", age = mean(NMES1988$age), income = mean(NMES1988$income), gender = "female", employed = "no", health="excellent", new.chronic=0)
# predict outcomes (responses) using 'predict()'
predicted.value.ins1healthe<-predict(model3, test.data.ins1healthe, type = "response")
# show predicted value
predicted.value.ins1healthe
```
